# Generated by Django 3.2.4 on 2021-06-25 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_auto_20210625_1055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='userid',
            field=models.CharField(max_length=64, verbose_name='사용자아이디'),
        ),
    ]
